# Goal in SE(3)
geometry_msgs/Pose left_target
geometry_msgs/Pose right_target
builtin_interfaces/Duration duration
---
# Result
bool success
---
# Feedback
float32 left_error_linear
float32 left_error_angular
float32 right_error_linear
float32 right_error_angular
