# Goal in SE(3)
float64[16] left_target
float64[16] right_target
string keyword
uint8 duration
---
# Result
bool success
---
# Feedback
float32 left_error_linear
float32 left_error_angular
float32 right_error_linear
float32 right_error_angular
